version: 1.0
  
description: A basic workflow that demonstrates error handler with continue.

vars:
  - message: null

tasks:
  task1:
    action: core.noop
    next:
      - when: <% succeeded() %>
        do: task2
      - when: <% failed() %>
        publish:
          - message: "$%#&@#$!!!"
        do: continue

  task2:
    action: core.noop
    next:
      - when: <% succeeded() %>
        publish:
          - message: "hooray!!!"

output:
  - message: <% ctx().message %>
